imports:
    - { resource: tables.yml }
services:
    alg.reqtpl.listener:
        class: alg\reqtpl\event\listener
        arguments:
            - @dbal.conn
            - @template
            - @user
            - @request
            - %core.root_path%
            - %core.php_ext%
            - @notification_manager
            - %tables.notifications%
            - %tables.reqtpl_fields%
            - %tables.reqtpl_options%
            - %tables.reqtpl_templates%
        tags:
            - { name: event.listener }
    alg.reqtpl.notification.type.reqtpl_manager:
        class: alg\reqtpl\notification\reqtpl_manager
        shared: false
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
            - [set_notifications_table, ['%tables.notifications%']]
        tags:
            - { name: notification.type }
